plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\49856\\WorkBuddy\\2026-08-10-09-51-07\\rork-medieval-3d-chess\\taptap-upload\\kings-gambit"
publishOrigin = "default"
base = "C:\\Users\\49856\\WorkBuddy\\2026-08-10-09-51-07\\rork-medieval-3d-chess\\taptap-upload\\kings-gambit"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]